### ISSUE TITLE
Page Detail's style displays error

### ISSUE THREAD

**Issue by gittig11** [zhanglun/lettura#42]
**Describe the bug**
After installing this app in Win10, page Detail's style displays error:
<img width="941" alt="Snipaste_2024-03-23_17-46-09" src="https://github.com/zhanglun/lettura/assets/14836440/50d61085-ca23-4f84-9269-ab3dba8ba16e">

**To Reproduce**
1. Install this app in Win10.
2. Check any rss.
3. Check any essay.
4. See error.

**Expected behavior**
Page Detail displays OK.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome
 - Version Version 122.0.6261.131 (Official Build) (64-bit)

**Comment by gittig11** [comment]
After checking the styles, I found that in `src\components\ArticleView\Detail.tsx`, the style is wrong:
```css
.max-w-\[calc\(var\(--reading-editable-line-width\)_\*_1px\)\] {
  max-width: calc(var(--reading-editable-line-width)* 1px);
}

--reading-editable-line-width: 1;
```

After fix the default line_width to minimun **504** rathen 1, this issue will be fixed.

PR: #43
